export const ADD_BOOKLIST = "ADD_BOOKLIST";
//BookList
export const DELETE_BOOKLIST = "DELETE_BOOKLIST";
export const FETCH_BOOKLIST="FETCH_BOOK_LIST"
export const FETCH_BOOKLIST_SUCCESS="FETCH_BOOK_LIST_SUCCESS"
export const FETCH_BOOKLIST_FAILURE="FETCH_BOOK_LIST_FAILURE"

//Ranking
export const FETCH_RANKING = "FETCH_RANKING";
export const FETCH_RANKING_SUCCESS = "FETCH_RANKING_SUCCESS";
export const FETCH_RANKING_FAILURE = "FETCH_RANKING_FAILURE";

//Login
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAILURE="LOGIN_FAILURE"
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS"
export const LOGOUT_FAILURE="LOGOUT_FAILURE"
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS"
export const SIGNUP_FAILURE="SIGNUP_FAILURE"
export const CHANGE_NAME="CHANGE_NAME"
export const CHANGE_PASS="CHANGE_PASS"
