export const ADD_BOOKLIST = "ADD_BOOKLIST";
//BookList
export const DELETE_BOOKLIST = "DELETE_BOOKLIST";
export const FETCH_BOOKLIST="FETCH_BOOK_LIST"
export const FETCH_BOOKLIST_SUCCESS="FETCH_BOOK_LIST_SUCCESS"
export const FETCH_BOOKLIST_FAILURE="FETCH_BOOK_LIST_FAILURE"

//Ranking
export const FETCH_RANKING = "FETCH_RANKING";
export const FETCH_RANKING_SUCCESS = "FETCH_RANKING_SUCCESS";
export const FETCH_RANKING_FAILURE = "FETCH_RANKING_FAILURE";
